"""01_initial-db

Revision ID: e684321cc9bc
Revises: 
Create Date: 2023-01-18 02:11:55.580757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e684321cc9bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления'),
    sa.Column('title', sa.String(length=20), nullable=False, comment='Название'),
    sa.Column('description', sa.String(length=50), nullable=True, comment='Описание'),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, comment='Идентификатор'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submenu',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления'),
    sa.Column('title', sa.String(length=20), nullable=False, comment='Название'),
    sa.Column('description', sa.String(length=50), nullable=True, comment='Описание'),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, comment='Идентификатор'),
    sa.Column('menu_id', postgresql.UUID(as_uuid=True), nullable=True, comment='Меню'),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dish',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, comment='Идентификатор'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления'),
    sa.Column('title', sa.String(length=20), nullable=False, comment='Название'),
    sa.Column('description', sa.String(length=50), nullable=True, comment='Описание'),
    sa.Column('price', sa.DECIMAL(precision=5, scale=2), nullable=False, comment='Цена'),
    sa.Column('submenu_id', postgresql.UUID(as_uuid=True), nullable=True, comment='Подменю'),
    sa.ForeignKeyConstraint(['submenu_id'], ['submenu.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dish')
    op.drop_table('submenu')
    op.drop_table('menu')
    # ### end Alembic commands ###
